### ISSUE TITLE
Stack: 계산기, 후위표현식

### ISSUE THREAD

**Issue by changicho** [burning-carrot/study-problem-solving#1]
**핵심 개념**

중위 표기법, 후위 표기법

- 중위 표기법은 연산자가 피연산자들의 사이에 위치
- 후위 표기법은 연산자가 피연산자들 뒤에 위치

```cpp
// 중위 표기법
(A + B) * (C + D)
// 후위 표기법
AB+CD+*
```

후위 표기식을 만들기 위해 자료구조 스택이 사용된다.

간단한 후위 표기법의 알고리즘은 다음으로 설계할 수 있다.

1. 피연산자는 스택에 넣지 않고 그냥 출력한다.
2. 연산자는 스택이 비었으면 스택에 push한다. 
3. 연산자는 스택이 비어있지 않으면 스택에 있는 연산자와의 우선순위를 비교해 스택에 있는 연산자의 우선순위가 같거나 크다면 스택에 있는 연산자를 pop을 한 후 출력하고 현재 연산자는 스택에 push한다.
4. 만약 3번에서 우선순위가 현재 연산자가 더 크면 현재 연산자를 push한다.(스택에서 pop하지 않음)
5. 수식이 끝나면 스택이 빌 때 까지 pop을 한 후 출력한다.

## 학습 링크

[삼성 SW 아카데미 스택 강의](https://swexpertacademy.com/main/learn/course/subjectDetail.do?courseId=AVuPDN86AAXw5UW6&subjectId=AV184uV6I70CFAZN)

[후위 표기법 계산 예시](https://eastroot1590.tistory.com/entry/%ED%9B%84%EC%9C%84-%ED%91%9C%EA%B8%B0%EB%B2%95-%EA%B3%84%EC%82%B0%EB%B2%95)

## 문제링크

이 문제를 먼저 풀어보세요!

[후위 표기식2](https://www.acmicpc.net/problem/1935)

다음 이 문제들을 풀어보세요!

[계산기1](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14mbSaAEwCFAYD&categoryId=AV14mbSaAEwCFAYD&categoryType=CODE)
[계산기2](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14nnAaAFACFAYD&categoryId=AV14nnAaAFACFAYD&categoryType=CODE)

마지막 문제들 까지 풀어보면 마스터!

[후위 표기식](https://www.acmicpc.net/problem/1918)
[계산기3](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14tDX6AFgCFAYD&categoryId=AV14tDX6AFgCFAYD&categoryType=CODE)

**Comment by Junow** [comment]
문제풀고 풀이 올리면 되나요?

**Comment by 2ssue** [comment]
> 문제풀고 풀이 올리면 되나요?

각자 branch를 따서 `problems/플랫폼/문제번호/작성자.확장자` 로 풀이한 문제를 올리고, master로 PR 보내실 때 어떻게 푸셨는지 같이 작성해주시면 됩니다🤩

풀이 양식은 찬기님이 올리신 [docs](https://github.com/burning-carrot/study-problem-solving/blob/master/docs/README.md) 참고해주세욥.

**Comment by Junow** [comment]
확인했습니당 😄

**Comment by Junow** [comment]
앞으로 어떤 주제들이 기다리고 있나요? 두근두근거리네여
